---
title: "covid19rmd"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(jsonlite)
library(dplyr)
library(tidyr)
library(purrr)
library(DT)
library(stringr)
```

```{r}
data <- "data/data.json" %>% 
  read_json() %>% 
  bind_rows()
```

Infections
=====================================  

Column {.sidebar}
-------------------------------------

```{r}

```

Column
-------------------------------------

### Data updated `now()`

```{r}
data_clean <- data %>% 
  separate(year_week, into = c("year", "week")) %>% 
  mutate(across(c(year, week), as.integer)) %>% 
  arrange(country, desc(year), desc(week)) %>% 
  distinct(country, .keep_all = T) %>% 
  select(country, continent, population, weekly_count, cumulative_count) %>% 
  mutate(weekly_count_pop = weekly_count / population,
         cumulative_count_pop = cumulative_count / population) %>% 
  mutate(across(where(is.numeric), round, digits = 4))

data_clean <- data_clean %>% 
  rename_all(~ gsub(., pattern = "_", replace = " ")) %>% 
  rename_all(str_to_title)

data_clean %>% 
  datatable(
    rownames = F, 
    options = list(orderClasses = T,
                   pageLength = 10,
                   lengthMenu = c(5, 10, 30, 50))
  )
```

